CREATE DATABASE bd_concursoproyectos
go
use bd_concursoproyectos
go
CREATE TABLE CATEGORIAS(
	IDCATEGORIA			int identity(1,1) NOT NULL,
	NOMBRECATEGORIA		varchar(50) NOT NULL
	PRIMARY KEY (IDCATEGORIA)
)

go
CREATE TABLE CONCURSO(
	IDCONCURSO		int identity(1,1) NOT NULL,
	IDCATEGORIA		int NOT NULL,
	TEMA			varchar(80) NOT NULL,
	INTEGRANTES		text NOT NULL,
	CURSO			varchar(50) NOT NULL,
	ASESOR			varchar(50) NOT NULL
	PRIMARY KEY (IDCONCURSO),
	FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS
)
go
